services:
  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    environment:
      - TZ=Asia/Bangkok
      - FASTAPI_ENV=${FASTAPI_ENV:-development}
      - FASTAPI_PORT=${FASTAPI_PORT:-8000}
    ports:
      - "${FASTAPI_PORT:-8000}:${FASTAPI_PORT:-8000}"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - frontend
  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    environment:
      - TZ=Asia/Bangkok
      - NODE_ENV=${NODE_ENV:-development}
      - VUE_PORT=${VUE_PORT:-5173}
    ports:
      - ${VUE_PORT:-5173}:${VUE_PORT:-5173}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped
  db:
    container_name: postgres_container
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-database}
      TZ: Asia/Bangkok
      PGTZ: Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis_container
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
